=== jimu-Z/dierci-test/RuoYi-Vue-master/ruoyi-system/src/main/resources/mapper/system/AgriLogisticsTempHumidityMapper.dtd
<!ELEMENT mapper ANY>
<!ATTLIST mapper namespace CDATA #IMPLIED>

<!ELEMENT resultMap ANY>
<!ATTLIST resultMap type CDATA #IMPLIED id CDATA #IMPLIED>

<!ELEMENT result ANY>
<!ATTLIST result property CDATA #IMPLIED column CDATA #IMPLIED>

<!ELEMENT sql ANY>
<!ATTLIST sql id CDATA #IMPLIED>

<!ELEMENT select ANY>
<!ATTLIST select id CDATA #IMPLIED parameterType CDATA #IMPLIED resultMap CDATA #IMPLIED>

<!ELEMENT insert ANY>
<!ATTLIST insert id CDATA #IMPLIED parameterType CDATA #IMPLIED useGeneratedKeys CDATA #IMPLIED keyProperty CDATA #IMPLIED>

<!ELEMENT update ANY>
<!ATTLIST update id CDATA #IMPLIED parameterType CDATA #IMPLIED>

<!ELEMENT delete ANY>
<!ATTLIST delete id CDATA #IMPLIED parameterType CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include refid CDATA #IMPLIED>

<!ELEMENT where ANY>

<!ELEMENT if ANY>
<!ATTLIST if test CDATA #IMPLIED>

<!ELEMENT trim ANY>
<!ATTLIST trim prefix CDATA #IMPLIED suffix CDATA #IMPLIED suffixOverrides CDATA #IMPLIED>

<!ELEMENT foreach ANY>
<!ATTLIST foreach item CDATA #IMPLIED collection CDATA #IMPLIED open CDATA #IMPLIED separator CDATA #IMPLIED close CDATA #IMPLIED>

=== jimu-Z/dierci-test/RuoYi-Vue-master/ruoyi-system/src/main/resources/mapper/system/AgriLogisticsTempHumidityMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper SYSTEM "AgriLogisticsTempHumidityMapper.dtd">
<mapper namespace="com.ruoyi.system.mapper.AgriLogisticsTempHumidityMapper">

    <resultMap type="AgriLogisticsTempHumidity" id="AgriLogisticsTempHumidityResult">
        <result property="recordId" column="record_id" />
        <result property="traceCode" column="trace_code" />
        <result property="orderNo" column="order_no" />
        <result property="deviceCode" column="device_code" />
        <result property="collectLocation" column="collect_location" />
        <result property="temperature" column="temperature" />
        <result property="humidity" column="humidity" />
        <result property="tempUpperLimit" column="temp_upper_limit" />
        <result property="tempLowerLimit" column="temp_lower_limit" />
        <result property="humidityUpperLimit" column="humidity_upper_limit" />
        <result property="humidityLowerLimit" column="humidity_lower_limit" />
        <result property="alertFlag" column="alert_flag" />
        <result property="alertMessage" column="alert_message" />
        <result property="collectTime" column="collect_time" />
        <result property="status" column="status" />
        <result property="createBy" column="create_by" />
        <result property="createTime" column="create_time" />
        <result property="updateBy" column="update_by" />
        <result property="updateTime" column="update_time" />
        <result property="remark" column="remark" />
    </resultMap>

    <sql id="selectAgriLogisticsTempHumidityVo">
        select record_id, trace_code, order_no, device_code, collect_location,
               temperature, humidity, temp_upper_limit, temp_lower_limit,
               humidity_upper_limit, humidity_lower_limit, alert_flag,
               alert_message, collect_time, status, remark,
               create_by, create_time, update_by, update_time
        from agri_logistics_temp_humidity
    </sql>

    <select id="selectAgriLogisticsTempHumidityList" parameterType="AgriLogisticsTempHumidity" resultMap="AgriLogisticsTempHumidityResult">
        <include refid="selectAgriLogisticsTempHumidityVo"/>
        <where>
            <if test="traceCode != null and traceCode != ''">
                and trace_code like concat('%', #{traceCode}, '%')
            </if>
            <if test="orderNo != null and orderNo != ''">
                and order_no like concat('%', #{orderNo}, '%')
            </if>
            <if test="deviceCode != null and deviceCode != ''">
                and device_code like concat('%', #{deviceCode}, '%')
            </if>
            <if test="alertFlag != null and alertFlag != ''">
                and alert_flag = #{alertFlag}
            </if>
            <if test="status != null and status != ''">
                and status = #{status}
            </if>
        </where>
        order by collect_time desc, record_id desc
    </select>

    <select id="selectAgriLogisticsTempHumidityByRecordId" parameterType="Long" resultMap="AgriLogisticsTempHumidityResult">
        <include refid="selectAgriLogisticsTempHumidityVo"/>
        where record_id = #{recordId}
    </select>

    <insert id="insertAgriLogisticsTempHumidity" parameterType="AgriLogisticsTempHumidity" useGeneratedKeys="true" keyProperty="recordId">
        insert into agri_logistics_temp_humidity
        <trim prefix="(" suffix=")" suffixOverrides=",">
            <if test="traceCode != null and traceCode != ''">trace_code,</if>
            <if test="orderNo != null and orderNo != ''">order_no,</if>
            <if test="deviceCode != null and deviceCode != ''">device_code,</if>
            <if test="collectLocation != null and collectLocation != ''">collect_location,</if>
            <if test="temperature != null">temperature,</if>
            <if test="humidity != null">humidity,</if>
            <if test="tempUpperLimit != null">temp_upper_limit,</if>
            <if test="tempLowerLimit != null">temp_lower_limit,</if>
            <if test="humidityUpperLimit != null">humidity_upper_limit,</if>
            <if test="humidityLowerLimit != null">humidity_lower_limit,</if>
            <if test="alertFlag != null and alertFlag != ''">alert_flag,</if>
            <if test="alertMessage != null and alertMessage != ''">alert_message,</if>
            <if test="collectTime != null">collect_time,</if>
            <if test="status != null and status != ''">status,</if>
            <if test="remark != null and remark != ''">remark,</if>
            <if test="createBy != null and createBy != ''">create_by,</if>
            create_time
        </trim>
        <trim prefix="values (" suffix=")" suffixOverrides=",">
            <if test="traceCode != null and traceCode != ''">#{traceCode},</if>
            <if test="orderNo != null and orderNo != ''">#{orderNo},</if>
            <if test="deviceCode != null and deviceCode != ''">#{deviceCode},</if>
            <if test="collectLocation != null and collectLocation != ''">#{collectLocation},</if>
            <if test="temperature != null">#{temperature},</if>
            <if test="humidity != null">#{humidity},</if>
            <if test="tempUpperLimit != null">#{tempUpperLimit},</if>
            <if test="tempLowerLimit != null">#{tempLowerLimit},</if>
            <if test="humidityUpperLimit != null">#{humidityUpperLimit},</if>
            <if test="humidityLowerLimit != null">#{humidityLowerLimit},</if>
            <if test="alertFlag != null and alertFlag != ''">#{alertFlag},</if>
            <if test="alertMessage != null and alertMessage != ''">#{alertMessage},</if>
            <if test="collectTime != null">#{collectTime},</if>
            <if test="status != null and status != ''">#{status},</if>
            <if test="remark != null and remark != ''">#{remark},</if>
            <if test="createBy != null and createBy != ''">#{createBy},</if>
            sysdate()
        </trim>
    </insert>

    <update id="updateAgriLogisticsTempHumidity" parameterType="AgriLogisticsTempHumidity">
        update agri_logistics_temp_humidity
        <trim prefix="SET" suffixOverrides=",">
            <if test="traceCode != null and traceCode != ''">trace_code = #{traceCode},</if>
            <if test="orderNo != null and orderNo != ''">order_no = #{orderNo},</if>
            <if test="deviceCode != null and deviceCode != ''">device_code = #{deviceCode},</if>
            <if test="collectLocation != null">collect_location = #{collectLocation},</if>
            <if test="temperature != null">temperature = #{temperature},</if>
            <if test="humidity != null">humidity = #{humidity},</if>
            <if test="tempUpperLimit != null">temp_upper_limit = #{tempUpperLimit},</if>
            <if test="tempLowerLimit != null">temp_lower_limit = #{tempLowerLimit},</if>
            <if test="humidityUpperLimit != null">humidity_upper_limit = #{humidityUpperLimit},</if>
            <if test="humidityLowerLimit != null">humidity_lower_limit = #{humidityLowerLimit},</if>
            <if test="alertFlag != null and alertFlag != ''">alert_flag = #{alertFlag},</if>
            <if test="alertMessage != null">alert_message = #{alertMessage},</if>
            <if test="collectTime != null">collect_time = #{collectTime},</if>
            <if test="status != null and status != ''">status = #{status},</if>
            <if test="remark != null">remark = #{remark},</if>
            <if test="updateBy != null and updateBy != ''">update_by = #{updateBy},</if>
            update_time = sysdate()
        </trim>
        where record_id = #{recordId}
    </update>

    <delete id="deleteAgriLogisticsTempHumidityByRecordId" parameterType="Long">
        delete from agri_logistics_temp_humidity where record_id = #{recordId}
    </delete>

    <delete id="deleteAgriLogisticsTempHumidityByRecordIds" parameterType="Long">
        delete from agri_logistics_temp_humidity where record_id in
        <foreach item="recordId" collection="array" open="(" separator="," close=")">
            #{recordId}
        </foreach>
    </delete>

    <select id="selectByTraceCodeWithTimeRange" parameterType="map" resultMap="AgriLogisticsTempHumidityResult">
        <include refid="selectAgriLogisticsTempHumidityVo"/>
        <where>
            trace_code = #{traceCode}
            <if test="collectTimeStart != null and collectTimeStart != ''">
                and collect_time >= #{collectTimeStart}
            </if>
            <if test="collectTimeEnd != null and collectTimeEnd != ''">
                and collect_time <![CDATA[<=]]> #{collectTimeEnd}
            </if>
        </where>
        order by collect_time asc
    </select>

</mapper>
